name: thedarclaud
favicon: null
layout_spectrum: 0.63466
typography_spectrum: 0.33683
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#525661'
    - '#ee6668'
    - '#aa9a9d'
    - '#98dbee'
    - '#1e1d22'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.11586278583854437
  rhythmicContrast: 0.5
purpose: []
