name: thedarclaud
favicon: null
layout_spectrum: 0.28134036902338266
typography_spectrum: 0.7514435492921621
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#525661'
    - '#ee6668'
    - '#aa9a9d'
    - '#98dbee'
    - '#1e1d22'
  brandStrength: 0.03787688771262765
  lightness: 0.25032708514481783
  saturation: 0.11586278583854437
  rhythmicContrast: 0.1793101013172418
purpose: []
